### ISSUE TITLE
Build is currently broken on current gftools

### ISSUE THREAD

**Issue by alerque** [tonsky/FiraCode#1105]
Building the font with `gftools` 0.3.14 is broken:

```
Traceback (most recent call last):
  File "/usr/bin/gftools-fix-vf-meta.py", line 206, in <module>
    main()
  File "/usr/bin/gftools-fix-vf-meta.py", line 196, in main
    update_nametable(roman_font)
  File "/usr/bin/gftools-fix-vf-meta.py", line 134, in update_nametable
    raise ValueError(f"Fvar instance coord {wght_val} needs to be "
ValueError: Fvar instance coord 450.0 needs to be within range 0-1000 and be a multiple of 100
```

This can be hacked around to build by disabling these two lines:

```bash
gftools fix-vf-meta $firaCodeVF
mv $firaCodeVF.fix $firaCodeVF
```

Obviously that isn't the right fix, but I don't know what is. Probably a map between the hundred-increment weight classes and the actual point on the weight interpolation scale you want it to map too. 

(Just checked and the latest `gftools` 0.4.0 is giving the same error.)

**Comment by tonsky** [comment]
Thanks for reporting! Unfortunately I have no idea what happened :(

**Comment by alerque** [comment]
I believe this changed 4-5 versions ago in `gftools`. It started being stricter about what it accepts as correct, and it now considers the current font source to be invalid. You even have a note about this in `googlefonts-qa/notes/QA-notes.md`. I didn't dig in upstream about why they made that change. The offending value is on line 122747 of the current Glyphs source.
