### ISSUE TITLE
Failed to load the firacode package

### ISSUE THREAD

**Issue by AxelDaguerre** [tonsky/FiraCode#774]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [firacode](https://github.com/tonsky/FiraCode) package 1.206.0

### Stack Trace

Failed to load the firacode package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:146559)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:688410)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:3550485)
    at measure (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:3537196)
    at Package.measure (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:3536028)
    at Package.load (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:3536769)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:381204)
    at config.transact (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:379627)
    at Config.transact (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:332146)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:11:379565)
    at t.loadState.then (~/AppData/Local/atom/app-1.37.0/resources/app/static/<embedded>:1:708589)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
atom-no-tab-close-icon 1.0.0 
color-picker 2.3.0 
firacode 1.206.0 
git-plus 8.6.3 
git-time-machine 2.1.0 
highlight-selected 0.16.0 
indent-guide-improved 1.4.13 
language-markdown 0.37.0 
purple-papers-syntax 0.1.1 
seti-icons 1.5.4 
split-diff 1.6.0 
sync-settings 0.8.6 
tree-view-copy-relative-path 1.2.0 
tree-view-git-branch 0.1.2 
```

Here is my error log, someone understand what is causing it ?

**Comment by j-f1** [comment]
It looks like some code is calling `require('firacode')`, which won’t work since the file that `require('firacode')` resolves to is a CSS file.

**Comment by AxelDaguerre** [comment]
thank you for the answer but i have to admit i didnt understand what you are trying to explain
